<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>injectionSelector</key>
	<string>source.ruby</string>
	<key>name</key>
	<string>Ruby debug</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((\bpp(\s+|\().*$)|\bputs.+?\.inspect\b)</string>
			<key>name</key>
			<string>debug.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.debug</string>
	<key>uuid</key>
	<string>4DF95755-1E72-4EB3-A627-5A1FA66BEF6B</string>
</dict>
</plist>
