<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>source.ruby</string>
	<key>name</key>
	<string>Ruby debug</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>debug.entity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\bpp(\s+|\().*$)|\bputs.+?(\.inspect|\*\d+)\b)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.debug</string>
	<key>uuid</key>
	<string>4DF95755-1E72-4EB3-A627-5A1FA66BEF6B</string>
</dict>
</plist>
